spring:
  application:
    name: FileBrowser
  datasource:
    url: jdbc:mysql://localhost:3306/file_browser?createDatabaseIfNotExist=true
    username: root
    password: 1234
app:
  files:
    location: files/